services:
  mind-journal-server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    env_file:
      - .env
    expose:
      - "80"
    networks:
      - reverse_proxy_network
    restart: unless-stopped

networks:
  reverse_proxy_network:
    external: true
